theme: jekyll-theme-slate
title: Standard fNIRS Metadata Project
logo:
description: The standardization of the fNIRS LSL Metadata intends to improve the interface of variety of devices and software with fNIRS from different manufacturers, reduce complexity in augmenting the fNIRS research with other technologies. 
